name: isolated_box
description: "Isolated Box for Hive project."
version: 0.0.2
publish_to: 'none'
repository: https://github.com/GoltVik/isolated_box.git

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true