name: isolated_box
description: "A Dart package providing an isolated box for the Hive database, enabling cross-isolate usage."
version: 1.0.1
repository: https://github.com/GoltVik/isolated_box

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.11.3
  path_provider: ^2.1.5

dev_dependencies:
  build_runner:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
  hive_ce_generator: ^1.9.2
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true