name: isolated_box
description: "A Dart package providing an isolated box for the Hive database, enabling cross-isolate usage."
version: 1.0.1
repository: https://github.com/GoltVik/isolated_box

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true