name: isolated_box
description: "Isolated Box for Hive project."
version: 0.0.3
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  build_runner:
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true