name: Publish to pub.dev

on:
  push:
    branches:
      - feature/publish_flow

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Setup Pub Credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/pub-credentials.json
          {
            "accessToken": "${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}",
            "refreshToken": "${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}",
            "tokenEndpoint": "${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}",
            "expiration": ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
          }
          EOF

      - name: Check Publish Warnings
        run: dart pub publish --dry-run

#      - name: Publish Package
#        run: dart pub publish -f